#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2021 Saso Kiselkov. All rights reserved.

# Prior to building the included dependencies, make sure the following
# packages are installed (tested on Ubuntu 18.04):
#	autoconf automake build-essential cmake gcc-multilib g++-multilib
#	mingw-w64 libgl1-mesa-dev libglu1-mesa-dev libtool libx11-dev
#	pkg-config qt5-default qt5-qmake unzip

logfile="$PWD/z_buildlog.txt"

export minimal=0
export no_tesseract=0

while getopts "cdmn" opt; do
	case $opt in
	c) export do_clean=1 ;;
	d) export do_dll=1 ;;
	n) export no_tesseract=1 ;;
	m)
		export minimal=1
		touch .minimal-deps
		;;
	esac
done

function pause(){
   echo "Press any key to continue"
   read -p "$*"
}

function clean_buildlog(){
    if [ -f "$logfile" ]; then
        rm "$logfile"
    fi
    echo "Previous log file deleted" 2>&1 | tee "$logfile"
}

function build_deps(){

if [[ "$minimal" == 0 ]]; then
	rm -f .minimal-deps
fi

if [[ "$do_clean" != 1 ]]; then
	git submodule init mingw-std-threads && \
	git submodule update --merge --recursive && \
	( cd mingw-std-threads && git checkout master )
fi

    ( cd libclipboard && ./build_libclipboard_deps && echo "=> Processed libclipboard" ) && \
    ( [ $minimal -eq 1 ] || ( cd libjpeg && ./build_libjpeg_deps && echo "=> Processed libjpg" ) ) && \
    # ( [ $minimal -eq 1 ] || [ $no_tesseract -eq 1 ] || ( cd ocr && ./build_ocr_deps && echo "=> Processed ocr" ) ) && \
    ( [ $minimal -eq 1 ] || ( cd openal-soft && ./build_openal && echo "=> Processed openal-soft" ) ) && \
    ( [ $minimal -eq 1 ] || ( cd cglm && ./build_cglm && echo "=> Processed cglm" ) ) && \
    ( [ $minimal -eq 1 ] || ( cd geographiclib && ./build_geographiclib && echo "=> Processed geographiclib" ) ) && \
    ( cd lzma/qmake && \
	if ( ! [ -f win-64/liblzma.a ] && [ "$minimal" -eq 0 ] ) || \
		! [ -f linux-64/liblzma.a ];
		then
		./build-win-lin
	fi
	)
	echo "=> All dependencies have been built"
}

clean_buildlog
build_deps 2>&1 | tee "$logfile"
