#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2017 Saso Kiselkov. All rights reserved.

# Invoke this script to build libacfutils for both Windows and Linux,
# 32- & 64-bit flavors. Install the necessary mingw cross-compile utilities
# first.
# On Linux also do "apt install libopenal-dev:x86_64 libopenal-dev:i386".

# We'll try to build on N+1 CPUs we have available. The extra +1 is to allow
# for one make instance to be blocking on disk.
NCPUS=$(( $(grep 'processor[[:space:]]\+:' /proc/cpuinfo  | wc -l) + 1 ))
RELEASE="debug"
DOCLEAN=1
DEBUG=0
NOERRORS=0

rm -rf win32 win64 lin32 lin64
mkdir -p win64 lin64

while getopts "DiE" opt; do
	case "$opt" in
	D)
		DEBUG=1
		;;
	i)
		DOCLEAN=0
		;;
	E)
		NOERRORS=1
		;;
	esac
done

if [[ "$DOCLEAN" == 1 ]]; then
	make distclean > /dev/null
fi
qmake -set DEBUG $DEBUG
qmake -set NOERRORS $NOERRORS
qmake -spec linux-g++-64 qmake-lin.pro && make -j $NCPUS && mv libacfutils.a lin64
if [ $? != 0 ] ; then
  exit
fi

if [[ "$DOCLEAN" != 0 ]]; then
	make distclean > /dev/null
fi
